/** Mirrors free-api-backend field schemas for instant UI without a schema API round-trip. */

const FIELD_SCHEMAS = {
  user: [
    "id",
    "uuid",
    "firstName",
    "lastName",
    "fullName",
    "email",
    "phone",
    "avatar",
    "username",
    "gender",
    "age",
    "dateOfBirth",
    "address",
    "company",
    "website",
    "createdAt",
  ],
  product: [
    "id",
    "title",
    "description",
    "price",
    "discount",
    "rating",
    "stock",
    "brand",
    "category",
    "releaseYear",
    "thumbnail",
    "images",
    "createdAt",
  ],
  post: ["id", "title", "body", "author", "tags", "likes", "comments", "publishedAt"],
  book: [
    "id",
    "title",
    "author",
    "isbn",
    "genre",
    "pages",
    "publisher",
    "publishedYear",
    "rating",
    "description",
    "createdAt",
  ],
  movie: [
    "id",
    "title",
    "director",
    "genre",
    "rating",
    "year",
    "duration",
    "cast",
    "description",
    "createdAt",
  ],
  recipe: [
    "id",
    "name",
    "ingredients",
    "instructions",
    "prepTime",
    "cookTime",
    "servings",
    "cuisine",
    "createdAt",
  ],
  comment: ["id", "body", "author", "postId", "likes", "createdAt"],
  photo: ["id", "title", "url", "thumbnail", "albumId", "description", "createdAt"],
  todo: ["id", "title", "completed", "userId", "priority", "dueDate", "createdAt"],
  album: [
    "id",
    "title",
    "artist",
    "genre",
    "year",
    "cover",
    "photoCount",
    "description",
    "createdAt",
  ],
  company: [
    "id",
    "name",
    "industry",
    "employees",
    "revenue",
    "website",
    "headquarters",
    "founded",
    "description",
    "createdAt",
  ],
  vehicle: [
    "id",
    "make",
    "model",
    "year",
    "vin",
    "color",
    "mileage",
    "fuelType",
    "price",
    "description",
    "createdAt",
  ],
  address: [
    "id",
    "street",
    "city",
    "state",
    "zipCode",
    "country",
    "latitude",
    "longitude",
    "createdAt",
  ],
} as const;

type SchemaType = keyof typeof FIELD_SCHEMAS;

const KEYWORD_MAP: Record<string, SchemaType> = {
  user: "user",
  users: "user",
  product: "product",
  products: "product",
  post: "post",
  posts: "post",
  book: "book",
  books: "book",
  movie: "movie",
  movies: "movie",
  film: "movie",
  films: "movie",
  recipe: "recipe",
  recipes: "recipe",
  comment: "comment",
  comments: "comment",
  photo: "photo",
  photos: "photo",
  todo: "todo",
  todos: "todo",
  album: "album",
  albums: "album",
  company: "company",
  companies: "company",
  vehicle: "vehicle",
  vehicles: "vehicle",
  car: "vehicle",
  cars: "vehicle",
  address: "address",
  addresses: "address",
};

export function getPredefinedFields(keyword: string): string[] | null {
  const type = KEYWORD_MAP[keyword.toLowerCase().trim()];
  if (!type) return null;
  return [...FIELD_SCHEMAS[type]];
}
