/**
 * Extracts available field names from an API response by deriving keys from data items.
 */
export function extractAvailableFields(response: unknown): string[] {
  return extractDataKeys(response);
}

/**
 * Extracts sorted unique top-level keys from `data` items in an API response.
 */
export function extractDataKeys(response: unknown): string[] {
  if (!response || typeof response !== "object") return [];

  const res = response as Record<string, unknown>;
  const data = res.data;

  if (data && typeof data === "object" && !Array.isArray(data)) {
    const keySet = new Set<string>();
    for (const key of Object.keys(data as Record<string, unknown>)) {
      keySet.add(key);
    }
    return Array.from(keySet).sort();
  }

  if (!Array.isArray(data) || data.length === 0) return [];

  const keySet = new Set<string>();
  for (const item of data) {
    if (item && typeof item === "object" && !Array.isArray(item)) {
      for (const key of Object.keys(item as Record<string, unknown>)) {
        keySet.add(key);
      }
    }
  }

  return Array.from(keySet).sort();
}

/**
 * Returns true when the API response was generated by AI.
 */
export function isAiResponse(response: unknown): boolean {
  if (!response || typeof response !== "object") return false;
  return (response as Record<string, unknown>).source === "ai";
}

/**
 * Returns a new response with each `data` item filtered to selected top-level keys.
 * The response envelope is preserved.
 */
export function filterResponseByFields(
  response: unknown,
  selectedFields: string[],
): unknown {
  if (!response || typeof response !== "object") return response;

  const res = response as Record<string, unknown>;
  const data = res.data;

  if (data && typeof data === "object" && !Array.isArray(data)) {
    const fieldSet = new Set(selectedFields);
    const filtered: Record<string, unknown> = {};
    for (const key of Object.keys(data as Record<string, unknown>)) {
      if (fieldSet.has(key)) {
        filtered[key] = (data as Record<string, unknown>)[key];
      }
    }
    return { ...res, data: filtered };
  }

  if (!Array.isArray(data) || data.length === 0) return response;

  const fieldSet = new Set(selectedFields);
  const filteredData = data.map((item) => {
    if (!item || typeof item !== "object" || Array.isArray(item)) return item;

    const filtered: Record<string, unknown> = {};
    for (const key of Object.keys(item as Record<string, unknown>)) {
      if (fieldSet.has(key)) {
        filtered[key] = (item as Record<string, unknown>)[key];
      }
    }
    return filtered;
  });

  return { ...res, data: filteredData };
}

/** True when the response `data` is a non-empty array (list endpoint). */
export function isListResponse(response: unknown): boolean {
  if (!response || typeof response !== "object") return false;
  const data = (response as Record<string, unknown>).data;
  return Array.isArray(data) && data.length > 0;
}

/** True when the response `data` is a single object (detail endpoint). */
export function isDetailResponse(response: unknown): boolean {
  if (!response || typeof response !== "object") return false;
  const data = (response as Record<string, unknown>).data;
  return Boolean(data && typeof data === "object" && !Array.isArray(data));
}

/** Extracts `id` values from a list response's `data` array (for list→detail UX). */
export function extractListItemIds(response: unknown, limit = 10): string[] {
  if (!response || typeof response !== "object") return [];

  const data = (response as Record<string, unknown>).data;
  if (!Array.isArray(data)) return [];

  return data
    .map((item) => {
      if (!item || typeof item !== "object" || Array.isArray(item)) return null;
      const id = (item as Record<string, unknown>).id;
      return id != null ? String(id) : null;
    })
    .filter((id): id is string => Boolean(id))
    .slice(0, limit);
}
