/**
 * Extracts available field names from an API response.
 * Prefers the backend `fields` metadata when present, otherwise derives from data items.
 */
export function extractAvailableFields(response: unknown): string[] {
  if (!response || typeof response !== "object") return [];

  const res = response as Record<string, unknown>;
  const metaFields = res.fields;

  if (
    Array.isArray(metaFields) &&
    metaFields.length > 0 &&
    metaFields.every((field) => typeof field === "string")
  ) {
    return [...metaFields].sort();
  }

  return extractDataKeys(response);
}

/**
 * Extracts sorted unique top-level keys from `data` items in an API response.
 */
export function extractDataKeys(response: unknown): string[] {
  if (!response || typeof response !== "object") return [];

  const res = response as Record<string, unknown>;
  const data = res.data;

  if (!Array.isArray(data) || data.length === 0) return [];

  const keySet = new Set<string>();
  for (const item of data) {
    if (item && typeof item === "object" && !Array.isArray(item)) {
      for (const key of Object.keys(item as Record<string, unknown>)) {
        keySet.add(key);
      }
    }
  }

  return Array.from(keySet).sort();
}

/**
 * Returns true when the API response was generated by AI.
 */
export function isAiResponse(response: unknown): boolean {
  if (!response || typeof response !== "object") return false;
  return (response as Record<string, unknown>).source === "ai";
}

/**
 * Returns a new response with each `data` item filtered to selected top-level keys.
 * The response envelope is preserved.
 */
export function filterResponseByFields(
  response: unknown,
  selectedFields: string[],
): unknown {
  if (!response || typeof response !== "object") return response;

  const res = response as Record<string, unknown>;
  const data = res.data;

  if (!Array.isArray(data) || data.length === 0) return response;

  const fieldSet = new Set(selectedFields);
  const filteredData = data.map((item) => {
    if (!item || typeof item !== "object" || Array.isArray(item)) return item;

    const filtered: Record<string, unknown> = {};
    for (const key of Object.keys(item as Record<string, unknown>)) {
      if (fieldSet.has(key)) {
        filtered[key] = (item as Record<string, unknown>)[key];
      }
    }
    return filtered;
  });

  return { ...res, data: filteredData };
}
